### ISSUE TITLE
Selection of Courses

### ISSUE THREAD

**Issue by markh55** [markh55/earnwhileyoulearn#3]
**User Story**

As a protection student, I want to explore a selection of courses on the website, so I can decide which course I might be interested in completing.

**Acceptance Criteria**

- [ ] The website has a separate page for the list of courses available.
- [ ] The course available page  should utilises the Bootstrap grid and card components for consistency in layout and responsiveness.
- [ ] Each card states the relevant title, image and descriptions.

**Tasks**

- [ ] Create a responsive Course available page featuring a handful of selected courses and their relevant details.
